language: rust
rust: nightly

os: linux

before_install:
 - nvm install 7
 - npm install
 - wget https://github.com/holochain/holochain-rust/releases/download/v0.0.8-alpha/cli-v0.0.8-alpha-x86_64-ubuntu-linux-gnu.tar.gz -O /tmp/cli-v0.0.8-alpha-x86_64-ubuntu-linux-gnu.tar.gz
 - tar -xvf /tmp/cli-v0.0.8-alpha-x86_64-ubuntu-linux-gnu.tar.gz
 - pwd
 - ls /hc
 - export PATH=$PATH:$PWD/hc

install:
 - rustup toolchain install nightly-2019-01-24
 - rustup default nightly-2019-01-24
 - rustup target add wasm32-unknown-unknown --toolchain nightly-2019-01-24

script:
 - cd hApp/
 - echo $PATH
 - hc test