language: rust
rust: nightly

os: linux

matrix:
  include:
    - language: node_js
      node_js: 7


before_install:
 - wget https://github.com/n1k0/casperjs/archive/1.0.2.tar.gz -O /tmp/casper.tar.gz
 - tar -xvf /tmp/casper.tar.gz
 - export PATH=$HOME/hc:$PATH

install:
 - rustup toolchain install nightly-2019-01-24
 - rustup default nightly-2019-01-24
 - rustup target add wasm32-unknown-unknown --toolchain nightly-2019-01-24

script:
 - cd /smartchainhApp/hApp
 - hc test