language: node_js
node_js:
  - "8"

services:
  - docker

env:
  global:
    - PROJECT_ID=smartchain
    - CLUSTER=standard-cluster-1
    - ZONE=europe-west1-b	
    - IMAGE_NAME=webapp

matrix:
  include:
      if: branch = staging
      env: IMAGE_NAME=webapp-test

stages:
  - test
  - name: deploy
    if: branch = master || branch = staging

jobs:
  include:
    - stage: "test"
      name: "Unit Tests"
      install:
        - npm install
      script: 
        - npm run test
    - script: 
        - npm run lint
      name: "Linting"
    - stage: "deploy"
      install:
        - npm install
      name: "Deploy to Google Cloud Kubernetes"
      script: 
        - npm run build
      before_deploy:
        - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash >/dev/null; fi
        - source /home/travis/google-cloud-sdk/path.bash.inc
        - gcloud --quiet version
        - gcloud --quiet components update
        - gcloud --quiet components update kubectl
      deploy:
        - provider: script
          script: chmod +x ./deploy-prod.sh && ./deploy-prod.sh
          skip_cleanup: true
          on:
            all_branches: true