apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: smartchain.timonchristiansen.com
    http:
      paths:
      - path: /
        backend:
          serviceName: webapp
          servicePort: 80
  - host: test.timonchristiansen.com
    http:
      paths:
      - path: /
        backend:
          serviceName: webapp-test
          servicePort: 80